openapi: 3.0.0
info:
  version: 1.0.0
  title: Stock Price Viewer API
  description: |
    This is a sample Stock Price Viewer Server based on the OpenAPI 3.0 specification.  
  contact:
    name: Justin Laws
    email: Jlaws12@liberty.edu
    
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/JLAWS12_1/YoutubeJay/1.0.0
  - description: Stock Price Viewer
    url: beta.jaylaws.com

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    Schema:
      type: object
      properties:
        id:
          type: integer
          format: int64
      description: Test Schema
