name: Swagger Online Editor Validation

on:
  push:
    branches:
      - main

jobs:
  validate-openapi-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y curl
      - name: Validate OpenAPI specs with Swagger Online Editor
        run: |
          for file in examples/*.yaml; do
            echo "Validating $file..."
            curl --location --request POST 'https://editor.swagger.io/api/validate' \
            --header 'Content-Type: application/yaml' \
            --data-binary "@$file" \
            --fail \
            --show-error \
            --silent || echo "::error file=$file::Validation failed for $file"
          done
