name: Swagger Online Editor Validation

on:
  push:
    branches:
      - main

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate OpenAPI specs using Swagger Online Editor
        run: |
          for file in examples/*.yaml; do
            echo "Validating $file..."
            response=$(curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -d "{\"spec\": \"$(cat $file | sed 's/\"/\\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')\"}" https://validator.swagger.io/validator/debug)
            if [ "$(echo "$response" | jq '.schemaValidationMessages | length')" -gt 0 ]; then
              echo "::error file=$file::Validation failed for $file"
              echo "$response" | jq .
            fi
          done
