name: Validate OpenAPI YAML files using char0n/swagger-editor-validate@v1

on:
  push:
    branches: [main]

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate OpenAPI YAML files
        uses: char0n/swagger-editor-validate@v1
        with:
          files: examples/*.yaml
          output-format: detailed
