name: Validate OpenAPI Specs

on:
  push:
    branches:
      - main

jobs:
  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      - name: Validate OpenAPI specs
        run: |
          for file in examples/*.yaml; do
            echo "Validating $file..."
            if swagger-cli validate "$file"; then
              echo "Validation succeeded for $file"
            else
              echo "Validation failed for $file"
              echo "------------------------"
              swagger-cli validate "$file" 2>&1 | sed -e "s|$PWD/||g"
              echo "------------------------"
              echo "::error file=$file::Validation failed for $file"
            fi
          done
