name: Swagger Online Editor Validation

on:
  push:
    branches:
      - main

jobs:
  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate OpenAPI specs
        run: |
          for file in examples/*.yaml; do
            echo "Validating $file..."
            response=$(curl -H "Content-Type: application/json" -X POST -d @$file https://validator.swagger.io/validator)
            if [[ $response == *"\"schemaValidationMessages\""* ]]; then
              echo "::error file=$file::$response"
            else
              echo "::debug file=$file::$response"
            fi
          done
