name: Validate YAML files using char0n/swagger-editor-validate@v1

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate YAML files
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: examples/*.yaml
          detailed-output: true
