name: Validate OpenAPI Specs

on:
  push:
    branches:
      - main

jobs:
  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      - name: Validate OpenAPI specs
        run: |
          for file in examples/*.yaml; do
            echo "Validating $file..."
            if swagger-cli validate --verbose "$file" > "$file.log" 2>&1; then
              echo "Validation succeeded for $file"
            else
              echo "::error file=$file::Validation failed for $file"
            fi
          done

      - name: Upload validation logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: validation-logs
          path: |
            examples/*.log
