name: Swagger-cli test

on:
  push:
    branches:
      - main

jobs:
  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install swagger-cli
        run: npm install -g swagger-cli
      - name: Validate OpenAPI specs
        run: |
          for file in examples/*.yaml; do
            echo "Validating $file..."
            swagger-cli validate "$file" || echo "::warning file=$file::Validation failed for $file"
          done
      - name: List validation errors
        run: |
          echo "Validation errors:"
          grep "::warning file=examples/" $GITHUB_WORKSPACE/*.log | sed -e 's/.*warning file=//' -e 's/::.*//' | sort -u | while read file; do
            echo "- $file"
            grep "::warning file=$file::" $GITHUB_WORKSPACE/*.log | sed -e 's/::.*//' -e 's/^.*warning /  - /' | sort -u
          done || true
