name: Validate OpenAPI Specs

on:
  push:
    branches:
      - main

jobs:
  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install papaparse-swagger
        run: npm install -g papaparse-swagger

      - name: Validate OpenAPI specs
        run: |
          for file in examples/*.yaml; do
            echo "Validating $file..."
            papaparse-swagger validate "$file" || echo "::error file=$file::Validation failed for $file"
          done
